# Name: Killian Daly
# Student number: 22739355
# I acknowledge DCU's adacemid integrity policy

make: myshell.c utility.c myshell.h
	@gcc -Wall myshell.c utility.c -o ../bin/myshell

# make clean can remove compiled files
clean:
	@rm -f ../bin/myshell
